k8s-controller-sidecars: Add missing namespace
After the discussion on
https://gerrit.wikimedia.org/r/c/988847/comment/fea5cdf6_8d05e483/ I
removed too many namespaces:

Error: release k8s-controller-sidecars failed, and has been uninstalled
due to atomic being set: ClusterRoleBinding.rbac.authorization.k8s.io
"sidecar-job-controller-viewer" is invalid: subjects[0].namespace:
Required value

The magic namespace field gets added to the namespaced objects, but that
doesn't mean it gets added to the subject of the RoleBinding.

Bug: T348284
Change-Id: I4cca8d8b426420e11d19acac6c2772ea130570d7