Revert "Fix wikifunctions orchestrator not using the service mesh"
This reverts commit dd8bfc16a35a04211f4830b1f8b55df9aa126844.

Reason for revert: Breaks wiki fetching, we probably don't have a header set

Change-Id: I82a23cb55fa04da94a2c6aa648a3bc32ec8b61bf
Error: FetchError: invalid json response body at http://localhost:6501/w/api.php?action=wikilambda_fetch&format=json&zids=Z10000