mediawiki: Remove duplicate definition of FCGI_URL
FCGI_URL is defined twice for the php container, which leads to helm
failing with a weird error:
Error: The order in patch list:
  [map[name:FCGI_URL value:0.0.0.0:9000] ...
   doesn't match $setElementOrder list:
  [map[name:SERVERGROUP] map[name:FCGI_MODE] map[name:FCGI_URL] ...

Change-Id: Id160a238aba32e24aa07bce97b9e472d74985500