Revert "dse-k8s-services Airflow: Bump image"
This reverts commit 7f38b81a51412d80d5c9c732208bf401f3913bcc.

Reason for revert: The mentioned commit caused issues in Airflow production. TypeError: FsArtifactSource.__init__() got an unexpected keyword argument 'fsspec_options'

Change-Id: Id36ea35bb7f7746ea620f5f83c9f07ae6daaf659