datahub-next: upgrade datahub to 0.13.3 (latest version) with upgraded jetty
Our previous attempt crashed with
```
java.lang.ClassNotFoundException: org.slf4j.LoggerFactory in file:///datahub/datahub-gms/scripts/jetty-jmx.xml
```

We have since realized that we needed to upgrade Jetty
(cf https://github.com/datahub-project/datahub/blob/master/docker/datahub-gms/Dockerfile#L29)
and have rebuilt the image in https://gitlab.wikimedia.org/repos/data-engineering/datahub/-/jobs/316269

We now perfom another attempt at upgrading datahub to 0.13.3

Bug: T363461
Change-Id: Ica9a61a0f7f8a2824a34adeb26819dbba4c91995