cirrus-streaming-updater: increase elasticsearch-bulk-max-action-size
The calculated value seems too low and triggers:
java.lang.IllegalArgumentException: The request entry sent to the buffer
was of size [10205204], when the maxRecordSizeInBytes was set to
[9437264].

Change-Id: I001c1dae6fa5582869587fa87542296d3336c4f5