Update cxserver to 2021-03-15-131520-production
Changes:
* charts:
  ** Bump cxserver chart to 0.0.22
  ** Use Prometheus instead of statsd metrics

* cxserver:
 ** 50eb7a3 - Fix MT error: TypeError: key.trim is not a function
 ** 4acfd9b - Use new metrics interface of servicerunner
 ** 76a1c59 - build: Updating eslint-config-wikimedia to 0.19.0
 ** a443e9d - Fixed typo "paramaters"
 ** 7089207 - Update dependencies

Bug: T271711
Bug: T201491
Bug: T271711
Bug: T240525
Bug: T207662
Change-Id: I963598aabb7406f4eab57d7fce63e575290adc48