Revert "admin_ng: Add Cassandra ServiceEntry and VS for LiftWing"
This reverts commit 4234209a00e8d85fdd6528e2c43dd8ac2d6928ed.

Reason for revert: Change does not apply:

> Error: UPGRADE FAILED: release knative-serving failed, and has been rolled back due to atomic being set: failed to create resource: admission webhook "validation.istio.io" denied the request: configuration is invalid: multiple hosts provided with non-HTTP, non-TLS ports

Change-Id: Iae2d8bbac128f4969708d5425b37a35a7918521f