airflow: ensure the pooler URI uses a terninated FQDN
This will make sure we bypass the DNS domain search, which _might_ be
what's causing the
```
psycopg2.OperationalError: could not translate host name "postgresql-airflow-search-pooler-rw.airflow-search" to address: Name or service not known
```
errors

Signed-off-by: Balthazar Rouberol <brouberol@wikimedia.org>
Bug: T383651
Change-Id: Ic28d49547d0b77016d6a45097232cf3421b1ef97